// This file is generated by npm run build:icons
// Do not edit manually

export type IconName =
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-top'
  | 'call-receive'
  | 'checkmark-small'
  | 'close'
  | 'equipment'
  | 'heart'
  | 'menu'
  | 'mortarboard'
  | 'scales'
  | 'search'
  | 'shopping-cart'
  | 'socials-messenger'
  | 'socials-tg'
  | 'socials-viber'
  | 'user'
  | 'vector'
  | 'view-grid'
